namespaceName: back-ns

backCafe:
  replicas: 1
  label: back-cafe-label
  name: back-cafe
  protocol: TCP
  host: aa0059100549f4ddba101319275ed534-554976623.us-east-1.elb.amazonaws.com
  containers:
    name: cafe-back-container
    contextPath: /api/v1
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 10
    mysqlDatabaseUrl: jdbc:mysql://mysql-cafe.mysql-ns.svc.cluster.local:3306/coffee_shop?allowPublicKeyRetrieval=true&useSSL=false
    containerPort: 80
    user:
    password:
    image:
      repository: kenu21/cafe-back-image
      tag:
