namespaceName: back-ns

backCafe:
  replicas: 1
  label: back-cafe-label
  name: back-cafe
  protocol: TCP
  host: aa0059100549f4ddba101319275ed534-554976623.us-east-1.elb.amazonaws.com
  containers:
    name: back-cafe-container
    mysqlDatabaseUrl: jdbc:mysql://mysql-cafe.mysql-ns.svc.cluster.local:3306/coffee_shop?allowPublicKeyRetrieval=true&useSSL=false
    containerPort: 80
    user:
    password:
    image:
      repository: kenu21/image-back-cafe
      tag:
