services:
  db:
    extends:
      file: ${COMPOSE_EXTENDS_PATH}
      service: db

  flyway:
    extends:
      file: ${COMPOSE_EXTENDS_PATH}
      service: flyway

  backend:
    build: .
    image: cafe-back-image:latest
    container_name: cafe-back-container
    restart: "on-failure:10"
    environment:
      MYSQL_DATABASE_URL: ${MYSQL_DATABASE_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      BACKEND_CONTAINER_PORT: ${BACKEND_CONTAINER_PORT}
      FRONTEND_LOCAL_PORT: ${FRONTEND_LOCAL_PORT}
      CONTEXT_PATH: ${CONTEXT_PATH}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "${BACKEND_LOCAL_PORT}:${BACKEND_CONTAINER_PORT}"
      - "5006:5005"
    networks:
      - cafenet
    depends_on:
      - flyway

networks:
  cafenet:
    name: cafenet
