spring:
  application:
    name: cafes

  datasource:
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

server:
  port: 80
  servlet:
    context-path: /api/v1
