apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-back-deployment
  namespace: {{ .Values.namespaceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-cafe
  template:
    metadata:
      labels:
        app: back-cafe
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - back
      containers:
        - name: back-container
          image: "{{ .Values.backCafe.image.repository }}:{{ .Values.backCafe.image.tag }}"
          ports:
            - containerPort: {{ .Values.backCafe.containerPort }}
          env:
            - name: MYSQL_USER
              value: {{ .Values.backCafe.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.backCafe.password }}
            - name: MYSQL_DATABASE_URL
              value: {{ .Values.backCafe.mysqlDatabaseUrl }}
