apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-cafe-deployment
  namespace: {{ .Values.namespaceName }}
spec:
  replicas: {{ .Values.backCafe.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backCafe.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.backCafe.label }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - back
      containers:
        - name: {{ .Values.backCafe.containers.name }}
          image: "{{ .Values.backCafe.containers.image.repository }}:{{ .Values.backCafe.containers.image.tag }}"
          ports:
            - containerPort: {{ .Values.backCafe.containers.containerPort }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.backCafe.containers.contextPath }}/actuator/health"
              port: {{ .Values.backCafe.containers.containerPort }}
            initialDelaySeconds: {{ .Values.backCafe.containers.initialDelaySeconds }}
            periodSeconds: {{ .Values.backCafe.containers.periodSeconds }}
            timeoutSeconds: {{ .Values.backCafe.containers.timeoutSeconds }}
            failureThreshold: {{ .Values.backCafe.containers.failureThreshold }}

          env:
            - name: MYSQL_DATABASE_URL
              value: {{ .Values.backCafe.containers.mysqlDatabaseUrl }}
            - name: MYSQL_USER
              value: {{ .Values.backCafe.containers.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.backCafe.containers.password }}
            - name: BACKEND_CONTAINER_PORT
              value: "{{ .Values.backCafe.containers.containerPort }}"
            - name: CONTEXT_PATH
              value: {{ .Values.backCafe.containers.contextPath }}
