apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress
  namespace: {{ .Values.namespaceName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.backCafe.host }}
      http:
        paths:
          - path: /cafe-back(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backCafe.name }}
                port:
                  number: {{ .Values.backCafe.containers.containerPort }}
