apiVersion: v1
kind: Service
metadata:
  name: cafe-back
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: back-cafe
  ports:
    - protocol: TCP
      port: {{ .Values.backCafe.containerPort }}
      targetPort: {{ .Values.backCafe.containerPort }}
  type: ClusterIP
