apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backCafe.name }}
  namespace: {{ .Values.namespaceName }}
spec:
  selector:
    app: {{ .Values.backCafe.label }}
  ports:
    - protocol: {{ .Values.backCafe.protocol }}
      port: {{ .Values.backCafe.containerPort }}
      targetPort: {{ .Values.backCafe.containerPort }}
  type: ClusterIP
